-- CreateTable
CREATE TABLE "verificaciones" (
    "id" TEXT NOT NULL,
    "nombreCompleto" TEXT NOT NULL,
    "tipoDocumento" TEXT NOT NULL,
    "numeroDocumento" TEXT NOT NULL,
    "celular" TEXT NOT NULL,
    "correoElectronico" TEXT NOT NULL,
    "direccion" TEXT NOT NULL,
    "ciudadMunicipio" TEXT NOT NULL,
    "fechaNacimiento" TIMESTAMP(3) NOT NULL,
    "edadCalculada" INTEGER NOT NULL,
    "ruralOUrbano" TEXT NOT NULL,
    "genero" TEXT NOT NULL,
    "estadoGestacion" TEXT NOT NULL,
    "nivelEstudio" TEXT NOT NULL,
    "tieneMedioTransporte" TEXT NOT NULL,
    "queMedioTransporte" TEXT,
    "numeroHijosMenores" INTEGER NOT NULL,
    "numeroHijosDiscapacitados" INTEGER NOT NULL,
    "estratoSocioeconomico" INTEGER NOT NULL,
    "ocupacion" TEXT NOT NULL,
    "semanasGestacion" INTEGER NOT NULL,
    "fechaTentativaParto" TIMESTAMP(3) NOT NULL,
    "ingresoHogar" TEXT NOT NULL,
    "esDesplazado" TEXT NOT NULL,
    "numeroPersonasCargo" TEXT NOT NULL,
    "estadoCivil" TEXT NOT NULL,
    "situacionLaboral" TEXT NOT NULL,
    "tipoVivienda" TEXT NOT NULL,
    "numeroPropiedades" TEXT NOT NULL,
    "tieneDiscapacidad" TEXT NOT NULL,
    "sisben" TEXT NOT NULL,
    "tieneAguaPotable" TEXT NOT NULL,
    "violenciaIntrafamiliar" TEXT NOT NULL,
    "fueExcluida" BOOLEAN NOT NULL,
    "razonExclusion" TEXT,
    "puntajeTotal" INTEGER,
    "esElegible" BOOLEAN,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verificaciones_pkey" PRIMARY KEY ("id")
);
